export type SupportedLanguage = 'en' | 'hi' | 'kn' | 'ta' | 'te';

export interface LanguageOption {
  code: SupportedLanguage;
  name: string;
  nativeName: string;
  flag: string;
}

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: 'en', name: 'English (Plain)', nativeName: 'English', flag: '🇬🇧' },
  { code: 'hi', name: 'Hindi (Plain)', nativeName: 'सरल हिंदी', flag: '🇮🇳' },
  { code: 'kn', name: 'Kannada (Plain)', nativeName: 'ಸರಳ ಕನ್ನಡ', flag: '🇮🇳' },
  { code: 'ta', name: 'Tamil (Plain)', nativeName: 'எளிய தமிழ்', flag: '🇮🇳' },
  { code: 'te', name: 'Telugu (Plain)', nativeName: 'సరళమైన తెలుగు', flag: '🇮🇳' }
];

export const VERNACULAR_DICTIONARY: Record<SupportedLanguage, Record<string, string>> = {
  en: {
    appName: 'ClarityLegal',
    tagline: 'Legal Information Accessibility Platform for Everyday People',
    homeTitle: 'Demystify Any Contract in Plain English & Vernacular',
    whatItMeans: '✨ What It Means',
    clauseReader: '🔍 Clause Reader',
    obligations: '📋 Obligations Matrix',
    timeline: '⏳ Next Steps',
    lawyerDossier: '💼 Lawyer Dossier',
    compareVersions: '🔄 Version Compare',
    originalPdf: '📄 Original PDF Canvas',
    structuredCards: '📑 Structured Clause Cards',
    executiveSummary: 'Executive Document Summary',
    jurisdiction: 'Jurisdiction',
    importantToReview: 'Important to Review',
    standardTerm: 'Standard Term',
    whyHighlighted: 'Why this is highlighted',
    pointsToDiscuss: 'Points to discuss or clarify',
    practicalScenario: 'Practical Scenario',
    viewInDoc: '👁️ Live Highlight in Document',
    yourObligations: 'Your Key Obligations',
    otherPartyObligations: "Other Party's Obligations",
    financialCommitments: 'Financial Commitments & Fees',
    deadlinesAndMilestones: 'Next Steps & Timeline Milestones',
    noContractNotice: 'No contractual obligations were identified in this document.',
    uncertainNotice: 'Document classification is uncertain. No contractual terms were assumed.',
    registrationAlert: '11-Month vs 12-Month Lease Rule (Section 17 Registration Act 1908)',
    modelTenancyTitle: 'State Tenancy Framework & Guidelines',
    disclaimer: 'ClarityLegal provides legal information accessibility and educational summaries, not licensed legal advice.',
    copyPoints: 'Copy Points',
    copied: 'Copied!',
    zoomIn: 'Zoom In',
    zoomOut: 'Zoom Out',
    fitWidth: 'Fit to Width',
    page: 'Page',
    of: 'of',
    liveHighlighted: '⚡ LIVE HIGHLIGHTED SECTION',
    whatIsThisDoc: 'What is this document?',
    whatMeansForYou: 'What does this document mean for you?',
    termOrDuration: 'Term / Duration',
    financialObligation: 'Financial Obligation',
    depositEscrow: 'Deposit / Escrow',
    sectionsToReview: 'Sections to Review',
    clausesNoted: 'Clauses Noted',
    clausesAssessed: 'Clauses Assessed',
    nonContractualNotice: 'Non-Contractual Record Detected',
    nonContractualDesc: 'This document was identified as a certificate, academic record, resume, or invoice rather than a binding contract. No contractual obligations were identified in this document. Contract metrics, risk flags, and timeline milestones do not apply.',
    uncertainTitle: 'Document Classification Uncertain',
    uncertainDesc: 'The system could not confidently verify whether this document constitutes an enforceable legal agreement or an informal memorandum. No contractual obligations or terms have been assumed. Professional legal review is recommended.',
    partiesInvolved: 'Identified Parties & Entities',
    partiesSubtitle: 'Click any party to inspect where their name and role appear in the document',
    legendAll: 'All Grounding',
    legendParties: 'Parties (Blue)',
    legendRisks: 'Risks & Flags (Red)',
    legendFinancials: 'Financials (Green)',
    legendObligations: 'Obligations (Purple)',
    legendTerms: 'Terms & Dates (Amber)',
    legendClauses: 'Clauses (Cyan)',
    searchPdf: 'Search in PDF...',
    prevPage: 'Previous Page',
    nextPage: 'Next Page',
    coordinateMarkers: 'coordinate markers',
    liveCanvasHighlight: '⚡ LIVE CANVAS HIGHLIGHT',
    exportBrief: 'Export Brief',
    uploadDoc: 'Upload Doc',
    coreResponsibilities: 'Core Responsibilities & Obligations',
    coreResponsibilitiesSubtitle: 'Side-by-side view of duties stated for each party',
    viewFullMatrix: 'View Full Matrix',
    whatRequiresOfYou: 'What the Document Requires of You',
    whatStatedForOther: 'What the Document Stated for the Other Party',
    whatHappensNext: 'What Happens Next? (Document Sequence)',
    whatHappensNextSubtitle: 'Sequence of events and timelines established by the document',
    fullTimeline: 'Full Timeline',
    action: 'Action',
    splitReaderTitle: 'Split-Pane Reader',
    splitReaderDesc: 'Read the original contract side-by-side with plain English explanations and reading mode toggles.',
    lawyerDossierTitle: 'Lawyer Preparation Dossier',
    lawyerDossierDesc: 'Specific questions to ask counsel, missing contract clauses, and evidence to gather before consultation.',
    compareDraftsTitle: 'Semantic Version Compare',
    compareDraftsDesc: 'Compare two versions of an agreement to see what specific terms changed.',
    chatTitle: 'Clarity AI Contract Assistant',
    chatSubtitle: 'Document Context & Clause References',
    chatPlaceholder: 'Ask anything about this document...',
    send: 'Send',
    settingsTitle: 'Platform Intelligence Settings',
    settingsSubtitle: 'Configure AI model and inference keys',
    save: 'Save',
    cancel: 'Cancel',
    timing: 'Timing',
    standard: 'Standard',
    presentInDoc: 'Present in Document',
    straightNo: 'Straight NO (Not Found in Document)'
  },
  hi: {
    appName: 'क्लेरिटी लीगल',
    tagline: 'आम नागरिकों के लिए कानूनी जानकारी को सरल बनाने वाला मंच',
    homeTitle: 'किसी भी अनुबंध को सरल हिंदी और अपनी भाषा में समझें',
    whatItMeans: '✨ इसका क्या अर्थ है',
    clauseReader: '🔍 खंड वाचक (क्लॉज रीडर)',
    obligations: '📋 जिम्मेदारियों की सूची',
    timeline: '⏳ आगामी कदम एवं समयरेखा',
    lawyerDossier: '💼 वकील परामर्श संक्षेप (डॉसियर)',
    compareVersions: '🔄 अनुबंध तुलना',
    originalPdf: '📄 मूल PDF दस्तावेज',
    structuredCards: '📑 व्यवस्थित खंड कार्ड',
    executiveSummary: 'दस्तावेज का संक्षिप्त सार',
    jurisdiction: 'कानूनी क्षेत्राधिकार',
    importantToReview: 'समीक्षा करना अत्यंत आवश्यक',
    standardTerm: 'सामान्य मानक शर्त',
    whyHighlighted: 'इसे क्यों रेखांकित किया गया है',
    pointsToDiscuss: 'चर्चा या स्पष्टीकरण के बिंदु',
    practicalScenario: 'व्यावहारिक उदाहरण / परिदृश्य',
    viewInDoc: '👁️ मूल दस्तावेज में देखें',
    yourObligations: 'आपकी मुख्य जिम्मेदारियां',
    otherPartyObligations: 'सामने वाले पक्ष की जिम्मेदारियां',
    financialCommitments: 'वित्तीय प्रतिबद्धताएं एवं शुल्क',
    deadlinesAndMilestones: 'महत्वपूर्ण समयसीमाएं एवं कदम',
    noContractNotice: 'इस दस्तावेज में कोई कानूनी बाध्यकारी दायित्व नहीं पाए गए।',
    uncertainNotice: 'दस्तावेज का कानूनी वर्गीकरण अनिश्चित है। कोई बाध्यकारी शर्तें नहीं मानी गई हैं।',
    registrationAlert: '11-माह बनाम 12-माह रेंट नियम (पंजीकरण अधिनियम 1908 की धारा 17)',
    modelTenancyTitle: 'राज्य किराया कानून एवं मॉडल किरायेदारी दिशानिर्देश',
    disclaimer: 'क्लेरिटी लीगल केवल सूचनात्मक और शैक्षणिक सहायता प्रदान करता है, यह पेशेवर कानूनी सलाह नहीं है।',
    copyPoints: 'सुझाव कॉपी करें',
    copied: 'कॉपी हो गया!',
    zoomIn: 'बड़ा करें',
    zoomOut: 'छोटा करें',
    fitWidth: 'चौड़ाई अनुसार सेट करें',
    page: 'पृष्ठ',
    of: 'का',
    liveHighlighted: '⚡ चयनित कानूनी खंड',
    whatIsThisDoc: 'यह दस्तावेज क्या है?',
    whatMeansForYou: 'इस दस्तावेज का आपके लिए क्या अर्थ है?',
    termOrDuration: 'अवधि / समयसीमा',
    financialObligation: 'वित्तीय देनदारी',
    depositEscrow: 'अमानत राशि (डिपॉजिट)',
    sectionsToReview: 'समीक्षा योग्य खंड',
    clausesNoted: 'खंड नोट किए गए',
    clausesAssessed: 'कुल विश्लेषित खंड',
    nonContractualNotice: 'गैर-संविदात्मक रिकॉर्ड पहचाना गया',
    nonContractualDesc: 'यह दस्तावेज प्रमाणपत्र, शैक्षणिक रिकॉर्ड, बायोडाटा या बिल के रूप में पहचाना गया है, न कि बाध्यकारी अनुबंध। इसमें कोई कानूनी बाध्यता नहीं है। अनुबंध संबंधी जोखिम और समयसीमा लागू नहीं होते।',
    uncertainTitle: 'दस्तावेज वर्गीकरण अनिश्चित है',
    uncertainDesc: 'प्रणाली निश्चित नहीं कर सकी कि यह कानूनी रूप से लागू होने वाला समझौता है या अनौपचारिक ज्ञापन। कोई बाध्यकारी शर्तें नहीं मानी गई हैं। कानूनी समीक्षा की सलाह दी जाती है।',
    partiesInvolved: 'पहचाने गए पक्ष और संस्थाएं',
    partiesSubtitle: 'दस्तावेज में किसी भी पक्ष का नाम और भूमिका देखने के लिए उन पर क्लिक करें',
    legendAll: 'सभी हाइलाइट्स',
    legendParties: 'पक्ष / नाम (नीला)',
    legendRisks: 'जोखिम एवं चेतावनियां (लाल)',
    legendFinancials: 'वित्तीय शर्तें एवं शुल्क (हरा)',
    legendObligations: 'जिम्मेदारियां एवं कर्तव्य (बैंगनी)',
    legendTerms: 'अवधि एवं तिथियां (अंबर)',
    legendClauses: 'समझौता खंड (हल्का नीला)',
    searchPdf: 'PDF में खोजें...',
    prevPage: 'पिछला पृष्ठ',
    nextPage: 'अगला पृष्ठ',
    coordinateMarkers: 'निर्देशांक मार्कर',
    liveCanvasHighlight: '⚡ मूल PDF में लाइव हाइलाइट',
    exportBrief: 'संक्षेप एक्सपोर्ट करें',
    uploadDoc: 'दस्तावेज अपलोड करें',
    coreResponsibilities: 'मुख्य जिम्मेदारियां एवं दायित्व',
    coreResponsibilitiesSubtitle: 'दोनों पक्षों के कर्तव्यों की आमने-सामने तुलना',
    viewFullMatrix: 'पूरी सूची देखें',
    whatRequiresOfYou: 'दस्तावेज के अनुसार आपकी जिम्मेदारियां',
    whatStatedForOther: 'सामने वाले पक्ष के कर्तव्य',
    whatHappensNext: 'आगे क्या होगा? (समयबद्ध कदम)',
    whatHappensNextSubtitle: 'दस्तावेज द्वारा निर्धारित घटनाओं और समयसीमा का क्रम',
    fullTimeline: 'पूरी समयरेखा',
    action: 'कदम',
    splitReaderTitle: 'विभाजित वाचक (स्प्लिट रीडर)',
    splitReaderDesc: 'मूल अनुबंध को सरल स्पष्टीकरण के साथ आमने-सामने पढ़ें।',
    lawyerDossierTitle: 'वकील परामर्श संक्षेप (डॉसियर)',
    lawyerDossierDesc: 'वकील से पूछने योग्य प्रश्न, छूटे हुए सुरक्षा खंड, और आवश्यक दस्तावेज।',
    compareDraftsTitle: 'अनुबंध प्रारूप तुलना',
    compareDraftsDesc: 'दो अनुबंधों की तुलना करके देखें कि क्या नियम और शर्तें बदली हैं।',
    chatTitle: 'क्लेरिटी AI कानूनी सहायक',
    chatSubtitle: 'दस्तावेज संदर्भ और खंड प्रमाण सहित',
    chatPlaceholder: 'इस दस्तावेज के बारे में कुछ भी पूछें...',
    send: 'भेजें',
    settingsTitle: 'मंच सेटिंग्स',
    settingsSubtitle: 'AI मॉडल एवं API कुंजी सेट करें',
    save: 'सुरक्षित करें',
    cancel: 'रद्द करें',
    timing: 'समय',
    standard: 'मानक',
    presentInDoc: 'दस्तावेज़ में मौजूद',
    straightNo: 'सीधा ना (दस्तावेज़ में नहीं मिला)'
  },
  kn: {
    appName: 'ಕ್ಲಾರಿಟಿ ಲೀಗಲ್',
    tagline: 'ಸಾಮಾನ್ಯ ಜನರಿಗೆ ಕಾನೂನು ಮಾಹಿತಿಯನ್ನು ಸರಳಗೊಳಿಸುವ ವೇದಿಕೆ',
    homeTitle: 'ಯಾವುದೇ ಒಪ್ಪಂದವನ್ನು ಸರಳ ಕನ್ನಡದಲ್ಲಿ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ',
    whatItMeans: '✨ ಇದರ ಅರ್ಥವೇನು',
    clauseReader: '🔍 ಕಲಮು ಓದುಗ (ಕ್ಲಾಸ್ ರೀಡರ್)',
    obligations: '📋 ಜವಾಬ್ದಾರಿಗಳ ಪಟ್ಟಿ',
    timeline: '⏳ ಮುಂದಿನ ಹಂತಗಳು ಮತ್ತು ವೇಳಾಪಟ್ಟಿ',
    lawyerDossier: '💼 ವಕೀಲರ ಸಮಾಲೋಚನೆ ದಾಖಲೆ',
    compareVersions: '🔄 ಆವೃತ್ತಿಗಳ ಹೋಲಿಕೆ',
    originalPdf: '📄 ಮೂಲ PDF ವೀಕ್ಷಣೆ',
    structuredCards: '📑 ವಿಂಗಡಿಸಲಾದ ಕಲಮುಗಳು',
    executiveSummary: 'ದಾಖಲೆಯ ಮುಖ್ಯಾಂಶಗಳ ಸಾರಾಂಶ',
    jurisdiction: 'ಕಾನೂನು ವ್ಯಾಪ್ತಿ',
    importantToReview: 'ಪರಿಶೀಲಿಸಬೇಕಾದ ಪ್ರಮುಖ ವಿಷಯ',
    standardTerm: 'ಸಾಮಾನ್ಯ ನಿಯಮಾವಳಿ',
    whyHighlighted: 'ಇದನ್ನು ಏಕೆ ಗುರುತಿಸಲಾಗಿದೆ',
    pointsToDiscuss: 'ಚರ್ಚಿಸಬೇಕಾದ ಅಥವಾ ಸ್ಪಷ್ಟಪಡಿಸಬೇಕಾದ ಅಂಶಗಳು',
    practicalScenario: 'ಪ್ರಾಯೋಗಿಕ ಸನ್ನಿವೇಶ',
    viewInDoc: '👁️ ದಾಖಲೆಯಲ್ಲಿ ನೇರವಾಗಿ ವೀಕ್ಷಿಸಿ',
    yourObligations: 'ನಿಮ್ಮ ಪ್ರಮುಖ ಕರ್ತವ್ಯಗಳು',
    otherPartyObligations: 'ಎದುರು ಪಕ್ಷದ ಕರ್ತವ್ಯಗಳು',
    financialCommitments: 'ಹಣಕಾಸಿನ ಬದ್ಧತೆಗಳು ಮತ್ತು ಶುಲ್ಕಗಳು',
    deadlinesAndMilestones: 'ಪ್ರಮುಖ ಗಡುವುಗಳು ಮತ್ತು ಹಂತಗಳು',
    noContractNotice: 'ಈ ದಾಖಲೆಯಲ್ಲಿ ಯಾವುದೇ ಬಾಧ್ಯತೆಯ ಕರಾರುಗಳು ಕಂಡುಬಂದಿಲ್ಲ.',
    uncertainNotice: 'ದಾಖಲೆಯ ವರ್ಗೀಕರಣ ಅನಿಶ್ಚಿತವಾಗಿದೆ. ಯಾವುದೇ ಕರಾರುಗಳನ್ನು ಊಹಿಸಲಾಗಿಲ್ಲ.',
    registrationAlert: '11-ತಿಂಗಳು vs 12-ತಿಂಗಳ ಬಾಡಿಗೆ ನಿಯಮ (ನೋಂದಣಿ ಕಾಯ್ದೆ 1908 ರ ಸೆಕ್ಷನ್ 17)',
    modelTenancyTitle: 'ಕರ್ನಾಟಕ ಮಾದರಿ ಬಾಡಿಗೆ ಕಾಯ್ದೆ ಮಾರ್ಗಸೂಚಿಗಳು',
    disclaimer: 'ಕ್ಲಾರಿಟಿ ಲೀಗಲ್ ಶೈಕ್ಷಣಿಕ ಮತ್ತು ಮಾಹಿತಿ ಉದ್ದೇಶಗಳಿಗಾಗಿ ಮಾತ್ರ, ಇದು ಕಾನೂನು ಸಲಹೆಯಲ್ಲ.',
    copyPoints: 'ಅಂಶಗಳನ್ನು ನಕಲಿಸಿ',
    copied: 'ನಕಲಿಸಲಾಗಿದೆ!',
    zoomIn: 'ದೊಡ್ಡದಾಗಿಸಿ',
    zoomOut: 'ಚಿಕ್ಕದಾಗಿಸಿ',
    fitWidth: 'ಅಗಲಕ್ಕೆ ಹೊಂದಿಸಿ',
    page: 'ಪುಟ',
    of: 'ರ',
    liveHighlighted: '⚡ ನೇರವಾಗಿ ಗುರುತಿಸಲಾದ ಭಾಗ',
    whatIsThisDoc: 'ಇದು ಯಾವ ರೀತಿಯ ದಾಖಲೆ?',
    whatMeansForYou: 'ಈ ದಾಖಲೆಯು ನಿಮಗಾಗಿ ಏನು ಸೂಚಿಸುತ್ತದೆ?',
    termOrDuration: 'ಅವಧಿ / ಕಾಲಾವಧಿ',
    financialObligation: 'ಹಣಕಾಸಿನ ಹೊಣೆಗಾರಿಕೆ',
    depositEscrow: 'ಠೇವಣಿ / ಮುಂಗಡ ಹಣ',
    sectionsToReview: 'ಪರಿಶೀಲಿಸಬೇಕಾದ ವಿಭಾಗಗಳು',
    clausesNoted: 'ಗುರುತಿಸಲಾದ ಕಲಮುಗಳು',
    clausesAssessed: 'ಒಟ್ಟು ವಿಶ್ಲೇಷಿಸಲಾದ ಕಲಮುಗಳು',
    nonContractualNotice: 'ಕರಾರಲ್ಲದ ದಾಖಲೆ ಗುರುತಿಸಲಾಗಿದೆ',
    nonContractualDesc: 'ಈ ದಾಖಲೆಯನ್ನು ಪ್ರಮಾಣಪತ್ರ, ಶೈಕ್ಷಣಿಕ ದಾಖಲೆ, ಅಥವಾ ಇನ್‌ವಾಯ್ಸ್ ಎಂದು ಗುರುತಿಸಲಾಗಿದೆ. ಇದರಲ್ಲಿ ಯಾವುದೇ ಕಾನೂನುಬದ್ಧ ಬಾಧ್ಯತೆಗಳಿಲ್ಲ.',
    uncertainTitle: 'ದಾಖಲೆಯ ವರ್ಗೀಕರಣ ಅನಿಶ್ಚಿತ',
    uncertainDesc: 'ಈ ದಾಖಲೆಯು ಕಾನೂನುಬದ್ಧ ಒಪ್ಪಂದವೇ ಅಥವಾ ಕೇವಲ ಜ್ಞಾಪಕ ಪತ್ರವೇ ಎಂಬುದನ್ನು ಖಚಿತಪಡಿಸಲಾಗಿಲ್ಲ. ವಕೀಲರ ಸಮಾಲೋಚನೆ ಸೂಕ್ತ.',
    partiesInvolved: 'ದಾಖಲೆಯಲ್ಲಿರುವ ಪಕ್ಷಗಳು ಮತ್ತು ಸಂಸ್ಥೆಗಳು',
    partiesSubtitle: 'ದಾಖಲೆಯಲ್ಲಿ ಹೆಸರು ಮತ್ತು ಪಾತ್ರವನ್ನು ವೀಕ್ಷಿಸಲು ಯಾವುದೇ ಪಕ್ಷದ ಮೇಲೆ ಕ್ಲಿಕ್ ಮಾಡಿ',
    legendAll: 'ಎಲ್ಲಾ ಹೈಲೈಟ್‌ಗಳು',
    legendParties: 'ಪಕ್ಷಗಳು / ಹೆಸರುಗಳು (ನೀಲಿ)',
    legendRisks: 'ಅಪಾಯಗಳು ಮತ್ತು ಎಚ್ಚರಿಕೆಗಳು (ಕೆಂಪು)',
    legendFinancials: 'ಹಣಕಾಸು ಮತ್ತು ಶುಲ್ಕಗಳು (ಹಸಿರು)',
    legendObligations: 'ಜವಾಬ್ದಾರಿಗಳು ಮತ್ತು ಕರ್ತವ್ಯಗಳು (ನೇರಳೆ)',
    legendTerms: 'ಅವಧಿ ಮತ್ತು ದಿನಾಂಕಗಳು (ಅಂಬರ್)',
    legendClauses: 'ಒಪ್ಪಂದದ ಕಲಮುಗಳು (ಸಯಾನ್)',
    searchPdf: 'PDF ನಲ್ಲಿ ಹುಡುಕಿ...',
    prevPage: 'ಹಿಂದಿನ ಪುಟ',
    nextPage: 'ಮುಂದಿನ ಪುಟ',
    coordinateMarkers: 'ಸ್ಥಳ ಗುರುತುಗಳು',
    liveCanvasHighlight: '⚡ ಮೂಲ PDF ನಲ್ಲಿ ನೇರ ಹೈಲೈಟ್',
    exportBrief: 'ಸಾರಾಂಶ ರಫ್ತು ಮಾಡಿ',
    uploadDoc: 'ದಾಖಲೆ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    coreResponsibilities: 'ಪ್ರಮುಖ ಜವಾಬ್ದಾರಿಗಳು ಮತ್ತು ಕರ್ತವ್ಯಗಳು',
    coreResponsibilitiesSubtitle: 'ಎರಡೂ ಪಕ್ಷಗಳ ಕರ್ತವ್ಯಗಳ ಮುಖಾಮುಖಿ ನೋಟ',
    viewFullMatrix: 'ಸಂಪೂರ್ಣ ಪಟ್ಟಿ ವೀಕ್ಷಿಸಿ',
    whatRequiresOfYou: 'ದಾಖಲೆಯ ಪ್ರಕಾರ ನಿಮ್ಮ ಜವಾಬ್ದಾರಿಗಳು',
    whatStatedForOther: 'ಎದುರು ಪಕ್ಷದ ಕರ್ತವ್ಯಗಳು',
    whatHappensNext: 'ಮುಂದೇನು ನಡೆಯುತ್ತದೆ? (ಕಾಲಾನುಕ್ರಮ)',
    whatHappensNextSubtitle: 'ದಾಖಲೆಯು ನಿಗದಿಪಡಿಸಿದ ಹಂತಗಳು ಮತ್ತು ಕಾಲಮಿತಿ',
    fullTimeline: 'ಸಂಪೂರ್ಣ ವೇಳಾಪಟ್ಟಿ',
    action: 'ಕ್ರಮ',
    splitReaderTitle: 'ವಿಭಜಿತ ಪರದೆ ಓದುಗ',
    splitReaderDesc: 'ಮೂಲ ಕರಾರನ್ನು ಸರಳ ಕನ್ನಡದ ವಿವರಣೆಯೊಂದಿಗೆ ಅಕ್ಕಪಕ್ಕದಲ್ಲಿ ಓದಿ.',
    lawyerDossierTitle: 'ವಕೀಲರ ಸಮಾಲೋಚನೆ ದಾಖಲೆ',
    lawyerDossierDesc: 'ವಕೀಲರನ್ನು ಕೇಳಬೇಕಾದ ಪ್ರಶ್ನೆಗಳು ಮತ್ತು ಮುನ್ನೆಚ್ಚರಿಕೆಗಳು.',
    compareDraftsTitle: 'ಕರಡು ಒಪ್ಪಂದಗಳ ಹೋಲಿಕೆ',
    compareDraftsDesc: 'ಎರಡು ಒಪ್ಪಂದಗಳ ನಡುವಿನ ವ್ಯತ್ಯಾಸಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.',
    chatTitle: 'ಕ್ಲಾರಿಟಿ AI ಕಾನೂನು ಸಹಾಯಕ',
    chatSubtitle: 'ದಾಖಲೆಯ ಸಂದರ್ಭ ಮತ್ತು ಕಲಮುಗಳ ಉಲ್ಲೇಖದೊಂದಿಗೆ',
    chatPlaceholder: 'ಈ ದಾಖಲೆಯ ಬಗ್ಗೆ ಏನನ್ನಾದರೂ ಕೇಳಿ...',
    send: 'ಕಳುಹಿಸಿ',
    settingsTitle: 'ವೇದಿಕೆ ಸಂಯೋಜನೆಗಳು',
    settingsSubtitle: 'AI ಮಾದರಿ ಮತ್ತು API ಕೀ ಕಾನ್ಫಿಗರ್ ಮಾಡಿ',
    save: 'ಉಳಿಸಿ',
    cancel: 'ರದ್ದುಮಾಡಿ',
    timing: 'ಸಮಯ',
    standard: 'ಪ್ರಮಾಣಿತ',
    presentInDoc: 'ದಾಖಲೆಯಲ್ಲಿ ಇದೆ',
    straightNo: 'ಖಚಿತವಾಗಿ ಇಲ್ಲ (ದಾಖಲೆಯಲ್ಲಿಲ್ಲ)'
  },
  ta: {
    appName: 'கிளாரிட்டி லீகல்',
    tagline: 'சாதாரண மக்களுக்கான எளிய சட்டத் தகவல் தளம்',
    homeTitle: 'எந்தவொரு ஒப்பந்தத்தையும் எளிய தமிழில் புரிந்து கொள்ளுங்கள்',
    whatItMeans: '✨ இதன் பொருள் என்ன',
    clauseReader: '🔍 ஒப்பந்தப் பிரிவு வாசிப்பான்',
    obligations: '📋 கடமைகள் பட்டியல்',
    timeline: '⏳ அடுத்த கட்ட நடவடிக்கைகள்',
    lawyerDossier: '💼 வழக்கறிஞர் ஆலோசனைக் குறிப்பு',
    compareVersions: '🔄 பதிப்புகள் ஒப்பீடு',
    originalPdf: '📄 அசல் PDF ஆவணம்',
    structuredCards: '📑 ஒழுங்கமைக்கப்பட்ட பிரிவுகள்',
    executiveSummary: 'ஆவணத்தின் சுருக்கம்',
    jurisdiction: 'சட்ட வரம்பு',
    importantToReview: 'கட்டாயம் மதிப்பாய்வு செய்ய வேண்டியவை',
    standardTerm: 'நிலையான விதிமுறை',
    whyHighlighted: 'இது ஏன் முன்னிலைப்படுத்தப்பட்டுள்ளது',
    pointsToDiscuss: 'விவாதிக்க வேண்டிய முக்கிய புள்ளிகள்',
    practicalScenario: 'நடைமுறைச் சூழல்',
    viewInDoc: '👁️ ஆவணத்தில் நேரடியாகக் காண்க',
    yourObligations: 'உங்கள் முக்கிய கடமைகள்',
    otherPartyObligations: 'எதிர் தரப்பின் கடமைகள்',
    financialCommitments: 'நிதிப் பொறுப்புகள் மற்றும் கட்டணங்கள்',
    deadlinesAndMilestones: 'காலக்கெடு மற்றும் முக்கிய மைல்கற்கள்',
    noContractNotice: 'இந்த ஆவணத்தில் சட்டப்பூர்வ கடமைகள் எதுவும் கண்டறியப்படவில்லை.',
    uncertainNotice: 'ஆவண வகைப்பாடு நிச்சயமற்றது. ஒப்பந்தக் கடமைகள் எதுவும் கருதப்படவில்லை.',
    registrationAlert: '11-மாத vs 12-மாத வாடகை விதி (பதிவுச் சட்டம் 1908 பிரிவு 17)',
    modelTenancyTitle: 'மாதிரி வாடகைச் சட்ட வழிகாட்டுதல்கள்',
    disclaimer: 'கிளாரிட்டி லீகல் தகவல் மற்றும் விழிப்புணர்வுக்காக மட்டுமே, இது சட்ட ஆலோசனை அல்ல.',
    copyPoints: 'நகலெடு',
    copied: 'நகலெடுக்கப்பட்டது!',
    zoomIn: 'பெரிதாக்கு',
    zoomOut: 'சிறிதாக்கு',
    fitWidth: 'பக்க அகலத்திற்கு மாற்று',
    page: 'பக்கம்',
    of: 'இல்',
    liveHighlighted: '⚡ முன்னிலைப்படுத்தப்பட்ட பிரிவு',
    whatIsThisDoc: 'இது என்ன வகையான ஆவணம்?',
    whatMeansForYou: 'இந்த ஆவணம் உங்களுக்கு எதை உணர்த்துகிறது?',
    termOrDuration: 'கால அளவு / திட்ட காலம்',
    financialObligation: 'நிதிப் பொறுப்பு',
    depositEscrow: 'முன்பணம் / வைப்புத் தொகை',
    sectionsToReview: 'மறுபரிசீலனை செய்ய வேண்டிய பிரிவுகள்',
    clausesNoted: 'குறிப்பிடப்பட்ட பிரிவுகள்',
    clausesAssessed: 'மொத்த ஆய்வுப் பிரிவுகள்',
    nonContractualNotice: 'ஒப்பந்தம் அல்லாத ஆவணம் கண்டறியப்பட்டது',
    nonContractualDesc: 'இந்த ஆவணம் சான்றிதழ், கல்விப் பதிவு அல்லது ரசீது என அடையாளம் காணப்பட்டுள்ளது. இதில் சட்டப்பூர்வ ஒப்பந்தக் கடமைகள் இல்லை.',
    uncertainTitle: 'ஆவண வகைப்பாடு நிச்சயமற்றது',
    uncertainDesc: 'இந்த ஆவணம் சட்டப்பூர்வமாக செல்லுபடியாகும் ஒப்பந்தமா என்பதை உறுதிப்படுத்த முடியவில்லை. வழக்கறிஞர் ஆலோசனை பரிந்துரைக்கப்படுகிறது.',
    partiesInvolved: 'ஆவணத்தில் உள்ள தரப்பினர் மற்றும் நிறுவனங்கள்',
    partiesSubtitle: 'ஆவணத்தில் அவர்களின் பெயர் மற்றும் பொறுப்பைக் காண ஏதேனும் ஒரு தரப்பினர் மீது கிளிக் செய்க',
    legendAll: 'அனைத்து அடையாளங்கள்',
    legendParties: 'தரப்பினர் / பெயர்கள் (நீலம்)',
    legendRisks: 'அபாயங்கள் & எச்சரிக்கைகள் (சிவப்பு)',
    legendFinancials: 'நிதிக் கடமைகள் & கட்டணம் (பச்சை)',
    legendObligations: 'பொறுப்புகள் & கடமைகள் (ஊதா)',
    legendTerms: 'காலக்கெடு & தேதிகள் (அம்பர்)',
    legendClauses: 'ஒப்பந்தப் பிரிவுகள் (சியான்)',
    searchPdf: 'PDF-ல் தேடுக...',
    prevPage: 'முந்தைய பக்கம்',
    nextPage: 'அடுத்த பக்கம்',
    coordinateMarkers: 'அமைவிடக் குறிகள்',
    liveCanvasHighlight: '⚡ அசல் PDF-ல் நேரடி அடையாளம்',
    exportBrief: 'சுருக்கத்தை ஏற்றுமதி செய்',
    uploadDoc: 'ஆவணத்தைப் பதிவேற்றுக',
    coreResponsibilities: 'முக்கிய பொறுப்புகள் மற்றும் கடமைகள்',
    coreResponsibilitiesSubtitle: 'இரு தரப்பு கடமைகளின் ஒப்பீடு',
    viewFullMatrix: 'முழு பட்டியலைக் காண்க',
    whatRequiresOfYou: 'ஆவணப்படி உங்கள் முக்கிய கடமைகள்',
    whatStatedForOther: 'எதிர் தரப்பின் கடமைகள்',
    whatHappensNext: 'அடுத்து என்ன நடக்கும்? (காலவரிசை)',
    whatHappensNextSubtitle: 'ஆவணத்தால் நிர்ணயிக்கப்பட்ட அடுத்த கட்ட நடவடிக்கைகள்',
    fullTimeline: 'முழு காலவரிசை',
    action: 'செயல்',
    splitReaderTitle: 'இருபக்க வாசிப்பான்',
    splitReaderDesc: 'அசல் ஒப்பந்தத்தையும் எளிய விளக்கத்தையும் அருகருகே படியுங்கள்.',
    lawyerDossierTitle: 'வழக்கறிஞர் ஆலோசனைக் குறிப்பு',
    lawyerDossierDesc: 'வழக்கறிஞரிடம் கேட்க வேண்டிய கேள்விகள் மற்றும் தேவையான ஆவணங்கள்.',
    compareDraftsTitle: 'வரைவு ஒப்பந்தங்களின் ஒப்பீடு',
    compareDraftsDesc: 'இரண்டு ஒப்பந்தங்களுக்கு இடையே உள்ள வேறுபாடுகளைக் கண்டறியவும்.',
    chatTitle: 'கிளாரிட்டி AI சட்ட உதவியாளர்',
    chatSubtitle: 'ஆவண சூழல் மற்றும் ஒப்பந்தப் பிரிவு ஆதாரங்களுடன்',
    chatPlaceholder: 'இந்த ஆவணத்தைப் பற்றி எதையும் கேளுங்கள்...',
    send: 'அனுப்புக',
    settingsTitle: 'தள அமைப்புகள்',
    settingsSubtitle: 'AI மாதிரி மற்றும் API சாவியை உள்ளிடவும்',
    save: 'சேமிக்க',
    cancel: 'ரத்து செய்',
    timing: 'நேரம்',
    standard: 'நிலையானது',
    presentInDoc: 'ஆவணத்தில் உள்ளது',
    straightNo: 'நேரடி இல்லை (ஆவணத்தில் காணப்படவில்லை)'
  },
  te: {
    appName: 'క్లారిటీ లీగల్',
    tagline: 'సాధారణ పౌరులకు చట్టపరమైన సమాచారాన్ని సులభతరం చేసే వేదిక',
    homeTitle: 'ఏ ఒప్పందాన్నైనా సరళమైన తెలుగులో సులభంగా అర్థం చేసుకోండి',
    whatItMeans: '✨ దీని అర్థం ఏమిటి',
    clauseReader: '🔍 నిబంధనల పాఠకుడు (క్లాజ్ రీడర్)',
    obligations: '📋 బాధ్యతల జాబితా',
    timeline: '⏳ తదుపరి దశలు & కాలక్రమం',
    lawyerDossier: '💼 న్యాయవాది సంప్రదింపు సారాంశం',
    compareVersions: '🔄 ఒప్పందాల పోలిక',
    originalPdf: '📄 అసలు PDF పత్రం',
    structuredCards: '📑 క్రమబద్ధీకరించిన నిబంధనలు',
    executiveSummary: 'పత్రం యొక్క సంక్షిప్త సారాంశం',
    jurisdiction: 'చట్టపరమైన పరిధి',
    importantToReview: 'తప్పక సమీక్షించవలసిన అంశాలు',
    standardTerm: 'ప్రామాణిక నిబంధన',
    whyHighlighted: 'ఇది ఎందుకు గుర్తించబడింది',
    pointsToDiscuss: 'చర్చించవలసిన లేదా స్పష్టం చేసుకోవలసిన అంశాలు',
    practicalScenario: 'ఆచరణాత్మక దృశ్యం',
    viewInDoc: '👁️ పత్రంలో నేరుగా చూడండి',
    yourObligations: 'మీ ముఖ్య బాధ్యతలు',
    otherPartyObligations: 'ఎదుటి పక్షం బాధ్యతలు',
    financialCommitments: 'ఆర్థిక నిబద్ధతలు & రుసుములు',
    deadlinesAndMilestones: 'ముఖ్యమైన గడువులు & దశలు',
    noContractNotice: 'ఈ పత్రంలో ఎలాంటి చట్టపరమైన బాధ్యతలు కనుగొనబడలేదు.',
    uncertainNotice: 'పత్రం వర్గీకరణ అనిశ్చితం. ఎలాంటి చట్టపరమైన షరతులు పరిగణించబడలేదు.',
    registrationAlert: '11-నెలల vs 12-నెలల లీజు నియమం (రిజిస్ట్రేషన్ చట్టం 1908 సెక్షన్ 17)',
    modelTenancyTitle: 'మోడల్ అద్దె చట్టం మార్గదర్శకాలు',
    disclaimer: 'క్లారిటీ లీగల్ కేవలం విద్యా మరియు సమాచార ప్రయోజనాల కోసమే, ఇది న్యాయ సలహా కాదు.',
    copyPoints: 'కాపీ చేయండి',
    copied: 'కాపీ అయ్యింది!',
    zoomIn: 'పెద్దది చేయి',
    zoomOut: 'చిన్నది చేయి',
    fitWidth: 'వెడల్పుకు సరిచేయి',
    page: 'పేజీ',
    of: 'లో',
    liveHighlighted: '⚡ ప్రత్యక్షంగా గుర్తించిన నిబంధన',
    whatIsThisDoc: 'ఇది ఎలాంటి పత్రం?',
    whatMeansForYou: 'ఈ పత్రం మీకు ఏం చెబుతోంది?',
    termOrDuration: 'కాలవ్యవధి / గడువు',
    financialObligation: 'ఆర్థిక బాధ్యత',
    depositEscrow: 'డిపాజిట్ / సెక్యూరిటీ నగదు',
    sectionsToReview: 'సమీక్షించాల్సిన విభాగాలు',
    clausesNoted: 'గుర్తించబడిన నిబంధనలు',
    clausesAssessed: 'మొత్తం విశ్లేషించిన నిబంధనలు',
    nonContractualNotice: 'ఒప్పందం కాని రికార్డు గుర్తించబడింది',
    nonContractualDesc: 'ఈ పత్రం సర్టిఫికేట్, విద్యా రికార్డు లేదా రసీదుగా గుర్తించబడింది. ఇందులో ఎలాంటి చట్టపరమైన బాధ్యతలు లేవు.',
    uncertainTitle: 'పత్రం వర్గీకరణ అనిశ్చితం',
    uncertainDesc: 'ఈ పత్రం చట్టపరంగా అమలు చేయగల ఒప్పందమా లేదా సాధారణ మెమోరండమా అనేది నిర్ధారించబడలేదు. న్యాయవాదిని సంప్రదించడం మంచిది.',
    partiesInvolved: 'పత్రంలోని పక్షాలు & సంస్థలు',
    partiesSubtitle: 'పత్రంలో పేరు మరియు బాధ్యతను చూడటానికి ఏదైనా పక్షంపై క్లిక్ చేయండి',
    legendAll: 'అన్ని గుర్తులు',
    legendParties: 'పక్షాలు / పేర్లు (నీలం)',
    legendRisks: 'ప్రమాదాలు & హెచ్చరికలు (ఎరుపు)',
    legendFinancials: 'ఆర్థిక నిబద్ధతలు & రుసుములు (ఆకుపచ్చ)',
    legendObligations: 'బాధ్యతలు & విధులు (ఊదా)',
    legendTerms: 'కాలపరిమితి & తేదీలు (అంబర్)',
    legendClauses: 'ఒప్పంద నిబంధనలు (సియాన్)',
    searchPdf: 'PDF లో వెతకండి...',
    prevPage: 'మునుపటి పేజీ',
    nextPage: 'తదుపరి పేజీ',
    coordinateMarkers: 'కోఆర్డినేట్ గుర్తులు',
    liveCanvasHighlight: '⚡ అసలు PDF లో ప్రత్యక్ష హైలైట్',
    exportBrief: 'సారాంశాన్ని ఎగుమతి చేయండి',
    uploadDoc: 'పత్రాన్ని అప్‌లోడ్ చేయండి',
    coreResponsibilities: 'ప్రధాన బాధ్యతలు & విధులు',
    coreResponsibilitiesSubtitle: 'రెండు పక్షాల విధుల పోలిక',
    viewFullMatrix: 'పూర్తి జాబితాను చూడండి',
    whatRequiresOfYou: 'పత్రం ప్రకారం మీ ప్రధాన బాధ్యతలు',
    whatStatedForOther: 'ఎదుటి పక్షం బాధ్యతలు',
    whatHappensNext: 'తర్వాత ఏమి జరుగుతుంది? (కాలక్రమం)',
    whatHappensNextSubtitle: 'పత్రం నిర్దేశించిన తదుపరి దశలు మరియు గడువులు',
    fullTimeline: 'పూర్తి కాలక్రమం',
    action: 'చర్య',
    splitReaderTitle: 'ద్విముఖ పాఠకుడు (స్ప్లిట్ రీడర్)',
    splitReaderDesc: 'అసలు పత్రాన్ని మరియు సరళమైన వివరణను పక్కపక్కనే చదవండి.',
    lawyerDossierTitle: 'న్యాయవాది సంప్రదింపు సారాంశం',
    lawyerDossierDesc: 'న్యాయవాదిని అడగవలసిన ప్రశ్నలు మరియు సేకరించాల్సిన ఆధారాలు.',
    compareDraftsTitle: 'ఒప్పంద ముసాయిదాల పోలిక',
    compareDraftsDesc: 'రెండు ఒప్పందాల మధ్య తేడాలను సులభంగా తెలుసుకోండి.',
    chatTitle: 'క్లారిటీ AI న్యాయ సహాయకుడు',
    chatSubtitle: 'పత్ర సందర్భం మరియు నిబంధనల ఆధారాలతో',
    chatPlaceholder: 'ఈ పత్రం గురించి ఏదైనా అడగండి...',
    send: 'పంపండి',
    settingsTitle: 'ప్లాట్‌ఫామ్ సెట్టింగ్‌లు',
    settingsSubtitle: 'AI మోడల్ మరియు API కీ అమర్చండి',
    save: 'భద్రపరచు',
    cancel: 'రద్దు చేయి',
    timing: 'సమయం',
    standard: 'ప్రామాణికం',
    presentInDoc: 'పత్రంలో ఉంది',
    straightNo: 'ఖచ్చితంగా లేదు (పత్రంలో కనుగొనబడలేదు)'
  }
};

export function getVernacularText(key: string, lang: SupportedLanguage = 'en'): string {
  const dict = VERNACULAR_DICTIONARY[lang] || VERNACULAR_DICTIONARY['en'];
  return dict[key] || VERNACULAR_DICTIONARY['en'][key] || key;
}
